### ISSUE TITLE
Two admins with same email break plsc

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#139]
In the case that two people with the same email address are an admin of a CO, plsc will fail to update the mail attribute of the CO. 
This scenario could happen on migration scenario's when the same user would (temporarily) be admin of a CO with two different account.

```
Oct 25 08:48:34 ldap-pf1 plsc[288157]: INFO:root:Initializing ldap: ldapi:///, sizelimit: 500
Oct 25 08:49:11 ldap-pf1 plsc[288157]: INFO:root:[LDAP] Update: o=surf_rsc.abelab,dc=ordered,dc=https://oauth2.live.surfresearchcloud.nl/saml/metadata/,dc=services,dc=sram,dc=surf,dc=nl
Oct 25 08:49:11 ldap-pf1 plsc[288157]: ERROR:root:Exception on modify of o=surf_rsc.xxxx,dc=ordered,dc=https://oauth2.live.surfresearchcloud.nl/saml/metadata/,dc=services,dc=sram,dc=surf,dc=nl: {'msgtype': 103, 'msgid': 15894, 'result': 20, 'desc': 'Type or value exists', 'ctrls': [], 'info': 'mail: value #0 provided more than once'}
Oct 25 08:49:11 ldap-pf1 plsc[288157]: ERROR:root:[(1, 'mail', None), (0, 'mail', [b'mXXXXX.rXXXXX@xx.nl', b'MXXXX.deGXXXXX@xx.nl', b'mXXXXX.bXXXXX@xxxx.nl', b'Mxxxxx.Rxxxxx@xx.nl'])]
Oct 25 08:49:11 ldap-pf1 plsc[288157]: Traceback (most recent call last):
Oct 25 08:49:11 ldap-pf1 plsc[288157]:   File "/opt/plsc/plsc_ordered.py", line 574, in <module>
Oct 25 08:49:11 ldap-pf1 plsc[288157]:     main()
Oct 25 08:49:11 ldap-pf1 plsc[288157]:   File "/opt/plsc/plsc_ordered.py", line 569, in main
Oct 25 08:49:11 ldap-pf1 plsc[288157]:     create(src, dst)
Oct 25 08:49:11 ldap-pf1 plsc[288157]:   File "/opt/plsc/plsc_ordered.py", line 268, in create
Oct 25 08:49:11 ldap-pf1 plsc[288157]:     dst.modify(co_dn, current_entry, co_entry)
Oct 25 08:49:11 ldap-pf1 plsc[288157]:   File "/opt/plsc/sldap.py", line 129, in modify
Oct 25 08:49:11 ldap-pf1 plsc[288157]:     raise e
Oct 25 08:49:11 ldap-pf1 plsc[288157]:   File "/opt/plsc/sldap.py", line 125, in modify
Oct 25 08:49:11 ldap-pf1 plsc[288157]:     self.__c.modify_s(dn, modlist)
Oct 25 08:49:11 ldap-pf1 plsc[288157]:   File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 427, in modify_s
Oct 25 08:49:11 ldap-pf1 plsc[288157]:     return self.modify_ext_s(dn,modlist,None,None)
Oct 25 08:49:11 ldap-pf1 plsc[288157]:   File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 400, in modify_ext_s
Oct 25 08:49:11 ldap-pf1 plsc[288157]:     resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
Oct 25 08:49:11 ldap-pf1 plsc[288157]:   File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 543, in result3
Oct 25 08:49:11 ldap-pf1 plsc[288157]:     resp_type, resp_data, resp_msgid, decoded_resp_ctrls, retoid, retval = self.result4(
Oct 25 08:49:11 ldap-pf1 plsc[288157]:   File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 553, in result4
Oct 25 08:49:11 ldap-pf1 plsc[288157]:     ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
Oct 25 08:49:11 ldap-pf1 plsc[288157]:   File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
Oct 25 08:49:11 ldap-pf1 plsc[288157]:     result = func(*args,**kwargs)
Oct 25 08:49:11 ldap-pf1 plsc[288157]: ldap.TYPE_OR_VALUE_EXISTS: {'msgtype': 103, 'msgid': 15894, 'result': 20, 'desc': 'Type or value exists', 'ctrls': [], 'info': 'mail: value #0 provided more than once'}
Oct 25 08:49:11 ldap-pf1 systemd[1]: plsc.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by mrvanes** [comment]
Can't reproduce?
```
$ ./plsc_ordered.py plsc.yml
INFO:root:Initializing ldap: ldaps://ldap1.scz-vm.net, sizelimit: 5
INFO:root:[LDAP] Update: o=ufra.research,dc=ordered,dc=a2a70b2a-a396-4fd3-96e5-d475acbf698a,dc=services,dc=vnet
```
![Image](https://github.com/user-attachments/assets/0e9419fb-843d-4b74-ae53-e1fd6959cf29)
![Image](https://github.com/user-attachments/assets/43a06071-e5f5-4ff3-bca2-1e1d151edccd)

**Comment by mrvanes** [comment]
Can't reproduce
