### ISSUE TITLE
Implementeer ldap paginatie in plsc om met meer dan 500/2000 leden per CO te kunnen omgaan.

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#26]
Ldap heeft een max aantal records die returned worden. Daar lopen we tegenaan, en daar moet plsc mee om kunnen gaan, door paginatie te doen.

Standaar staat de limiet in openldap op 500 records; op onze machines is dat nu opgehoogd tot 2000.  Dat is dus het max aantal gebruiker dat totaal in 1 keer door een ldapquery kan worden opgevraagd (en dus het max aantal user per dienst)

**Comment by baszoetekouw** [comment]
Werk na de PR #29 nog niet goed op test.  
Ik heb verschillende sizelimits geprobeerd (tussen 500 en 50) maar krijg steeds dit:

```
jul 05 09:39:43 app1-tf1 systemd[1]: Starting PLSC Runner...
jul 05 09:39:44 app1-tf1 run.sh[1119897]: INFO:root:Initializing ldap: ldapi:///, sizelimit: 500
jul 05 09:40:45 app1-tf1 run.sh[1119897]: Traceback (most recent call last):
jul 05 09:40:45 app1-tf1 run.sh[1119897]:   File "/opt/plsc/plsc_ordered.py", line 491, in <module>
jul 05 09:40:45 app1-tf1 run.sh[1119897]:     main()
jul 05 09:40:45 app1-tf1 run.sh[1119897]:   File "/opt/plsc/plsc_ordered.py", line 487, in main
jul 05 09:40:45 app1-tf1 run.sh[1119897]:     cleanup(dst)
jul 05 09:40:45 app1-tf1 run.sh[1119897]:   File "/opt/plsc/plsc_ordered.py", line 409, in cleanup
jul 05 09:40:45 app1-tf1 run.sh[1119897]:     organizations = dst.rfind(f"dc=ordered,dc={service}",
jul 05 09:40:45 app1-tf1 run.sh[1119897]:   File "/opt/plsc/sldap.py", line 103, in rfind
jul 05 09:40:45 app1-tf1 run.sh[1119897]:     return self.find(b, ldap_filter, attrs, scope)
jul 05 09:40:45 app1-tf1 run.sh[1119897]:   File "/opt/plsc/sldap.py", line 87, in find
jul 05 09:40:45 app1-tf1 run.sh[1119897]:     r = self.__search(basedn, ldap_filter, attrs, scope)
jul 05 09:40:45 app1-tf1 run.sh[1119897]:   File "/opt/plsc/sldap.py", line 66, in __search
jul 05 09:40:45 app1-tf1 run.sh[1119897]:     _, rdata, _, serverctrls = self.__c.result3(page)
jul 05 09:40:45 app1-tf1 run.sh[1119897]:   File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 543, in result3
jul 05 09:40:45 app1-tf1 run.sh[1119897]:     resp_type, resp_data, resp_msgid, decoded_resp_ctrls, retoid, retval = self.result4(
jul 05 09:40:45 app1-tf1 run.sh[1119897]:   File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 553, in result4
jul 05 09:40:45 app1-tf1 run.sh[1119897]:     ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
jul 05 09:40:45 app1-tf1 run.sh[1119897]:   File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
jul 05 09:40:45 app1-tf1 run.sh[1119897]:     result = func(*args,**kwargs)
jul 05 09:40:45 app1-tf1 run.sh[1119897]: ldap.SIZELIMIT_EXCEEDED: {'msgtype': 101, 'msgid': 30106, 'result': 4, 'desc': 'Size limit exceeded', 'ctrls': []}
jul 05 09:40:45 app1-tf1 systemd[1]: plsc.service: Main process exited, code=exited, status=1/FAILURE
jul 05 09:40:45 app1-tf1 systemd[1]: plsc.service: Failed with result 'exit-code'.
jul 05 09:40:45 app1-tf1 systemd[1]: Failed to start PLSC Runner.
jul 05 09:40:45 app1-tf1 systemd[1]: plsc.service: Consumed 5.082s CPU time.
```

**Comment by mrvanes** [comment]
Dit is interessant, sizelimit lijkt niks te maken te hebben met paging en kan dus net zo goed op unlimited gezet worden als ik het goed begrijp? https://lists.ucc.gu.uwa.edu.au/pipermail/tech/2016-March/004735.html

Ik kan met sizelimit wel het gedrag van de search beinvloeden (meer loops) dus olcSizeLimit gaat inderdaad over de maximale size van het resultaat en niet van een page. Best een onzinnige setting dus, zoals de page hierboven beschrijft!?

Nouja, het heeft natuurlijk wel zin als je niet wil dat een (stom) filter veel te veel results oplevert, maar voor plsc heeft het dus geen zin

**Comment by baszoetekouw** [comment]
nog checken dat al sizelimits nu op unlimited staan
