### ISSUE TITLE
plsc_flat faalt als er een gebruikers bestaan met gelijke `uid`s en `cn`s

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#36]
Reproduceer als volgt:
- pak laatste main versie van scz-deploy (met @mrvanes's OIDC-OP changes)
- deploy
- clear en seed SBS
- log uit en in als admin/admin
- draai plsc_ordered
- draai plsc_flat

Dat geeft:
```
ERROR:root:Exception on modify of uid=admin,ou=People,dc=flat,dc=https://wiki,dc=services,dc=vnet: {'msgtype': 103, 'msgid': 452, 'result': 19, 'desc': 'Constraint violation', 'ctrls': [], 'info': 'eduPersonUniqueId: multiple values provided'}
ERROR:root:[(1, 'eduPersonUniqueId', None), (0, 'eduPersonUniqueId', [b'admin', b'urn:admin']), (1, 'displayName', None), (0, 'displayName', [b'SCZ Admin', b'The Boss']), (1, 'givenName', None), (0, 'givenName', [b'n/a', b'Admin']), (1, 'sn', None), (0, 'sn', [b'n/a', b'SCZ']), (1, 'cn', None), (0, 'cn', [b'admin', b'urn:admin']), (1, 'mail', None), (0, 'mail', [b'boss@example.org', b'admin@scz-vm.net']), (1, 'uid', None), (0, 'uid', [b'admin', b'ascz']), (0, 'voPersonExternalAffiliation', [b'member']), (0, 'voPersonExternalID', [b'admin']), (0, 'voPersonPolicyAgreement;time-1652947518', [b'https://google.nl'])]
Traceback (most recent call last):
  File "/home/ansible/plsc/plsc_flat.py", line 188, in <module>
    create(src, dst)
  File "/home/ansible/plsc/plsc_flat.py", line 73, in create
    ldif = dst.store(dst_dn, src_entry)
  File "/home/ansible/plsc/sldap.py", line 111, in store
    return self.modify(dn, entry, new_entry)
  File "/home/ansible/plsc/sldap.py", line 101, in modify
    raise e
  File "/home/ansible/plsc/sldap.py", line 97, in modify
    self.__c.modify_s(dn, modlist)
  File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 427, in modify_s
    return self.modify_ext_s(dn,modlist,None,None)
  File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 400, in modify_ext_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 543, in result3
    resp_type, resp_data, resp_msgid, decoded_resp_ctrls, retoid, retval = self.result4(
  File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 553, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
    result = func(*args,**kwargs)
ldap.CONSTRAINT_VIOLATION: {'msgtype': 103, 'msgid': 452, 'result': 19, 'desc': 'Constraint violation', 'ctrls': [], 'info': 'eduPersonUniqueId: multiple values provided'}
```

Er zijn in deze situatie idd twee "admin"-users: `cn=admin/uid=ascz` (uit de OIDC login) en `cn=urn:admin/uid=admin` (uit de seed).  

Deze lijken door `plsc_flat` op 1 hoop te worden gegooid.  Het lijkt alsof plsc_flat de uid van de ene vergelijkt met de cn van de andere.  Als ik namelijk van `cn=urn:admin` de uid verander in `admin_seed` werkt alles opeens goed.

Zal in de praktijk niet voorkomen (want we krijgen uuid-achtige `cn`s van eduTEAMS, maar moeten we wel even fixen)

**Comment by mrvanes** [comment]
Alle stappen doorlopen, maar kan niet reproduceren. Vrijdag even samen naar kijken?
![image](https://user-images.githubusercontent.com/1901782/172635455-891004d5-f6f7-4daf-96a5-7ce14d2ee4cb.png)

**Comment by baszoetekouw** [comment]
Kan het idd niet meer reproduceren...
