### ISSUE TITLE
Verandering van displayname leidt tot plsc error

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#51]
Als iemand al een displayname heeft in de flat en er wordt een andere (geupdate) gesynct, dan faalt plsc als volgt:

```
Aug 29 11:25:48 ldap-pf1 run.sh[995548]: INFO:root:[LDAP] Update: uid=gxyzxyzyxz,ou=People,dc=flat,dc=https://oauth2.live.surfresearchcloud.nl/saml/metadata/,dc=services,dc=sram,dc=surf,dc=nl
Aug 29 11:25:48 ldap-pf1 run.sh[995548]: ERROR:root:Exception on modify of uid=gxyzxyzyxz,ou=People,dc=flat,dc=https://oauth2.live.surfresearchcloud.nl/saml/metadata/,dc=services,dc=sram,dc=surf,dc=nl: {'msgtype': 103, 'msgid': 986, 'result': 19, 'desc': 'Constraint violation', 'ctrls': [], 'info': 'displayName: multiple values provided'}
Aug 29 11:25:48 ldap-pf1 run.sh[995548]: ERROR:root:[(1, 'displayName', None), (0, 'displayName', [b'B.G. xyzxyzyxz', b'Gyzxyzx Rxyzxyzxyz'])]
Aug 29 11:25:48 ldap-pf1 run.sh[995548]: Traceback (most recent call last):
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:   File "/opt/plsc/plsc_flat.py", line 195, in <module>
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:     create(src, dst)
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:   File "/opt/plsc/plsc_flat.py", line 72, in create
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:     ldif = dst.store(dst_dn, src_entry)
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:   File "/opt/plsc/sldap.py", line 112, in store
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:     return self.modify(dn, entry, new_entry)
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:   File "/opt/plsc/sldap.py", line 102, in modify
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:     raise e
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:   File "/opt/plsc/sldap.py", line 98, in modify
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:     self.__c.modify_s(dn, modlist)
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:   File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 427, in modify_s
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:     return self.modify_ext_s(dn,modlist,None,None)
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:   File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 400, in modify_ext_s
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:     resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:   File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 543, in result3
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:     resp_type, resp_data, resp_msgid, decoded_resp_ctrls, retoid, retval = self.result4(
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:   File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 553, in result4
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:     ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:   File "/opt/plsc/venv/lib/python3.9/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
Aug 29 11:25:48 ldap-pf1 run.sh[995548]:     result = func(*args,**kwargs)
Aug 29 11:25:48 ldap-pf1 run.sh[995548]: ldap.CONSTRAINT_VIOLATION: {'msgtype': 103, 'msgid': 986, 'result': 19, 'desc': 'Constraint violation', 'ctrls': [], 'info': 'displayName: multiple values provided'}
Aug 29 11:25:48 ldap-pf1 systemd[1]: plsc.service: Main process exited, code=exited, status=1/FAILURE
```

Probleem heb ik nu eenmalig verholpen door bij de desbetreffende entry in de flat tree de displayName te verwijderen.  De update daarna ging het weer goed.

Probleem zit hier: https://github.com/SURFscz/plsc/blob/main/plsc_flat.py#L66-L72
Deze code zorgt ervoor dat attributen nooit kunnen veranderen; hooguit kunnen er nieuwe waardes worden toegevoegd.
Dat lijtk me niet de bedoeling.  Deze attributenmerge moet dus slimmer.

**Comment by baszoetekouw** [comment]
Eenvoudig te reproduceren: draai plsc, verander daarna in de flat tree van 1 gebruiker de displayName, en draai plsc opnieuw --> fail.

**Comment by HarryKodden** [comment]
Analyse heeft opgeleverd dat de merging van attributen in de FLAT subtree niet moet gebeuren. De herkomst van de code om te mergen is ontwerp idee uit verleden om te mergen met de data die mogelijk ook is geupdate door de service. Dit is niet langer het geval. Uitsluitend SRAM PLSC is de bron voor updates.
